### ISSUE TITLE
推荐使用c++

### ISSUE THREAD

**Issue by hanxuanliang** [Nick17t/LC-DailyQuestion#1]
因为 `java` 的集合框架很丰富，推荐使用c++的stl来写题。
毕竟博主现在还年轻，c++比较锻炼码力

**Comment by hey-sa** [comment]
谢谢你的建议哦。之所以用JAVA写是因为我最近报名了蓝桥杯的JAVA组，所以在用java刷题hhh。等比赛结束后，我会学习使用C++刷题的！

**Comment by hanxuanliang** [comment]
🔨 👊
